version: '3.6'
services:
    web:
        image: meamzy/magento:installed
        container_name: web
        restart: always
        user: root
        environment:
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - /home/ubuntu/magento:/app:cached
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
          - "9000:9000"
        links:
          - mysql
          - elasticsearch
        
    elasticsearch:
        container_name: elasticsearch
        image: markoshust/magento-elasticsearch:7.7.1-0
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          - "discovery.type=single-node"
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
        ports:
          - "8080:80"
        links:
          - mysql:db
        depends_on:
          - mysql
volumes:
    db-data: 
        external: false
